/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    sponsors: SponsorAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sponsors: Sponsor;
    events: Event;
    plans: Plan;
    forms: Form;
    'piezas-redes-sociales': PiezasRedesSociale;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'piezas-redes-sociales': PiezasRedesSocialesSelect<false> | PiezasRedesSocialesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Sponsor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SponsorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Se autocompleta con el nombre del archivo si se deja en blanco.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  eventsSummary?: string | null;
  currentPlanName?: string | null;
  companyName: string;
  logo?: (number | null) | Media;
  contactInfo?: {
    fullName?: string | null;
    whatsapp?: string | null;
    corporateEmail?: string | null;
    linkedin?: string | null;
  };
  whatsappGroup?: {
    link?: string | null;
    joined?: boolean | null;
  };
  documents?:
    | {
        name?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  eventParticipations?:
    | {
        isCurrent?: boolean | null;
        event: number | Event;
        plan: number | Plan;
        strategy?: {
          description?: string | null;
          eventObjectives?: string | null;
          brandDifferentiator?: string | null;
        };
        meetings?:
          | {
              name?: string | null;
              projectedMonth?: string | null;
              calendlyLink?: string | null;
              platform?: string | null;
              status?: ('pending' | 'scheduled' | 'completed') | null;
              scheduledDate?: string | null;
              id?: string | null;
            }[]
          | null;
        deliverables?:
          | {
              /**
               * Enlace estable con el plan. No editar.
               */
              planDeliverableId?: string | null;
              benefitCategory?: string | null;
              itemName?: string | null;
              type?: ('document' | 'image' | 'text' | 'link' | 'direct' | 'action_link' | 'formulario') | null;
              actionUrl?: string | null;
              status?: ('pending' | 'completed' | 'overdue') | null;
              dueDate?: string | null;
              /**
               * Opcional. Si se define, el entregable se habilita a partir de esta fecha. Sin fecha usa la lógica secuencial.
               */
              unlockDate?: string | null;
              uploadedFile?: (number | null) | Media;
              uploadedText?: string | null;
              uploadedLink?: string | null;
              /**
               * Ítems del beneficio que desbloquea este entregable.
               */
              relatedItemNames?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              /**
               * Selecciona el formulario que debe completar el sponsor.
               */
              formId?: (number | null) | Form;
              formResponse?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              source?: ('plan' | 'custom') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Ítems heredados del plan. Sube evidencias aquí para marcarlos como completados.
         */
        benefitItems?:
          | {
              /**
               * Enlace estable con el plan. No editar.
               */
              planBenefitItemId?: string | null;
              benefitCategory?: string | null;
              itemName?: string | null;
              status?: ('not_started' | 'in_progress' | 'completed') | null;
              evidences?:
                | {
                    type: 'image' | 'document' | 'text' | 'link';
                    file?: (number | null) | Media;
                    text?: string | null;
                    link?: string | null;
                    id?: string | null;
                  }[]
                | null;
              source?: ('plan' | 'custom') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Asigna piezas creadas en la colección "Piezas de Redes Sociales". El sponsor podrá verlas y descargarlas desde su portal.
         */
        redesSociales?:
          | {
              pieza: number | PiezasRedesSociale;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'sponsors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  endDate: string;
  logo?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  location?: {
    venue?: string | null;
    city?: string | null;
    country?: string | null;
    details?: string | null;
  };
  /**
   * Configura el único calendario de este evento, añadiendo sus diferentes momentos e ítems.
   */
  journey?: {
    moments?:
      | {
          momentTitle: string;
          items?:
            | {
                itemTitle: string;
                date1: string;
                date2?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Estas reuniones se clonarán al Sponsor cuando se le asigne este evento.
   */
  meetingTemplates?:
    | {
        name: string;
        /**
         * Ej: "Octubre 2026" o un selector de fecha referencial.
         */
        projectedMonth?: string | null;
        calendlyLink?: string | null;
        platform?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  addonsDiscount?: number | null;
  benefits?:
    | {
        benefitName: string;
        hasDeliverable?: boolean | null;
        /**
         * Opcional. Si se define, todos los entregables de esta categoría se habilitan a partir de esta fecha. Cada entregable puede tener su propia fecha que sobreescribe esta.
         */
        unlockDate?: string | null;
        deliverables?:
          | {
              deliverableName: string;
              type: 'document' | 'image' | 'text' | 'link' | 'direct' | 'action_link' | 'formulario';
              actionUrl?: string | null;
              /**
               * Selecciona el formulario que debe completar el sponsor.
               */
              formId?: (number | null) | Form;
              dueDate: string;
              /**
               * Opcional. Sobreescribe la fecha de la categoría para este entregable específico. Si no se define, se usa la de la categoría.
               */
              unlockDate?: string | null;
              /**
               * Selecciona los ítems del beneficio a los que aplica este entregable.
               */
              relatedItems?:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[]
          | null;
        items?:
          | {
              itemName: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Ej: "Así se verá tu video en el evento". Se muestra al sponsor antes de los campos del formulario.
   */
  referenceTitle?: string | null;
  /**
   * El sponsor verá una miniatura clicable que abre la imagen a pantalla completa.
   */
  referenceImage?: (number | null) | Media;
  /**
   * Se abrirá en una nueva pestaña al hacer clic.
   */
  referencePdf?: (number | null) | Media;
  /**
   * URL de ejemplo. Se muestra como botón al sponsor.
   */
  referenceLink?: string | null;
  fields?:
    | {
        label: string;
        fieldKey?: string | null;
        type: 'text' | 'textarea' | 'number' | 'date' | 'select' | 'checkbox' | 'image' | 'link' | 'email';
        required?: boolean | null;
        placeholder?: string | null;
        options?:
          | {
              optionLabel: string;
              optionValue: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Para piezas de tipo Imagen o PDF sube el archivo aquí. Para links deja el archivo vacío y rellena el campo URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piezas-redes-sociales".
 */
export interface PiezasRedesSociale {
  id: number;
  nombre: string;
  formatoTipo: 'imagen' | 'pdf' | 'link';
  /**
   * Solo para formato Link.
   */
  urlLink?: string | null;
  fechaPublicacion?: string | null;
  copySugerido?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'piezas-redes-sociales';
        value: number | PiezasRedesSociale;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'sponsors';
        value: number | Sponsor;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'sponsors';
        value: number | Sponsor;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  eventsSummary?: T;
  currentPlanName?: T;
  companyName?: T;
  logo?: T;
  contactInfo?:
    | T
    | {
        fullName?: T;
        whatsapp?: T;
        corporateEmail?: T;
        linkedin?: T;
      };
  whatsappGroup?:
    | T
    | {
        link?: T;
        joined?: T;
      };
  documents?:
    | T
    | {
        name?: T;
        file?: T;
        id?: T;
      };
  eventParticipations?:
    | T
    | {
        isCurrent?: T;
        event?: T;
        plan?: T;
        strategy?:
          | T
          | {
              description?: T;
              eventObjectives?: T;
              brandDifferentiator?: T;
            };
        meetings?:
          | T
          | {
              name?: T;
              projectedMonth?: T;
              calendlyLink?: T;
              platform?: T;
              status?: T;
              scheduledDate?: T;
              id?: T;
            };
        deliverables?:
          | T
          | {
              planDeliverableId?: T;
              benefitCategory?: T;
              itemName?: T;
              type?: T;
              actionUrl?: T;
              status?: T;
              dueDate?: T;
              unlockDate?: T;
              uploadedFile?: T;
              uploadedText?: T;
              uploadedLink?: T;
              relatedItemNames?: T;
              formId?: T;
              formResponse?: T;
              source?: T;
              id?: T;
            };
        benefitItems?:
          | T
          | {
              planBenefitItemId?: T;
              benefitCategory?: T;
              itemName?: T;
              status?: T;
              evidences?:
                | T
                | {
                    type?: T;
                    file?: T;
                    text?: T;
                    link?: T;
                    id?: T;
                  };
              source?: T;
              id?: T;
            };
        redesSociales?:
          | T
          | {
              pieza?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  logo?: T;
  backgroundImage?: T;
  location?:
    | T
    | {
        venue?: T;
        city?: T;
        country?: T;
        details?: T;
      };
  journey?:
    | T
    | {
        moments?:
          | T
          | {
              momentTitle?: T;
              items?:
                | T
                | {
                    itemTitle?: T;
                    date1?: T;
                    date2?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  meetingTemplates?:
    | T
    | {
        name?: T;
        projectedMonth?: T;
        calendlyLink?: T;
        platform?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  addonsDiscount?: T;
  benefits?:
    | T
    | {
        benefitName?: T;
        hasDeliverable?: T;
        unlockDate?: T;
        deliverables?:
          | T
          | {
              deliverableName?: T;
              type?: T;
              actionUrl?: T;
              formId?: T;
              dueDate?: T;
              unlockDate?: T;
              relatedItems?: T;
              id?: T;
            };
        items?:
          | T
          | {
              itemName?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  referenceTitle?: T;
  referenceImage?: T;
  referencePdf?: T;
  referenceLink?: T;
  fields?:
    | T
    | {
        label?: T;
        fieldKey?: T;
        type?: T;
        required?: T;
        placeholder?: T;
        options?:
          | T
          | {
              optionLabel?: T;
              optionValue?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "piezas-redes-sociales_select".
 */
export interface PiezasRedesSocialesSelect<T extends boolean = true> {
  nombre?: T;
  formatoTipo?: T;
  urlLink?: T;
  fechaPublicacion?: T;
  copySugerido?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}